services:
  - type: web
    name: islamic-ai-assistant
    env: python
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false 